# Используем образ SDK для сборки приложения
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Копируем файл проекта и восстанавливаем зависимости
COPY Mesenger/Mesenger.csproj Mesenger/
COPY Application/Application.csproj Application/
COPY Domain/Domain.csproj Domain/
COPY Infrastructure/Infrastructure.csproj Infrastructure/

RUN dotnet restore Mesenger/Mesenger.csproj

# Копируем остальные файлы и собираем приложение
COPY . .
WORKDIR /src/Mesenger
RUN dotnet publish Mesenger.csproj -c Release -o /app/publish

# Используем минимальный runtime образ для запуска приложения
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Указываем порт, на котором приложение будет работать
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080

# Запуск приложения
ENTRYPOINT ["dotnet", "Mesenger.dll"]
