version: '3.4'

services:
  mesenger:
    image: ${DOCKER_REGISTRY-}mesenger
    build:
      context: .
      dockerfile: Mesenger/Dockerfile
    ports:
        - "51870:8080"
        - "51871:8081"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
